### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by JulianKahnert** [PDF-Archiver/pdf-archiver.github.io#27]
Add user stories and reference websites (picture and text) to the `cta` section.

**Comment by MattAndDev** [comment]
Hey hi 👋!

I have a small proposal for this one, what you think about [this](https://github.com/MattAndDev/pdf-archiver.github.io/pull/1)

**Comment by JulianKahnert** [comment]
This looks awesome!! 😍 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
