### ISSUE TITLE
FAQ/Help page

### ISSUE THREAD

**Issue by JulianKahnert** [PDF-Archiver/pdf-archiver.github.io#5]
the following links should be updated:
* [ ] in App: menu bar help link
* [ ] link in README.md
* [ ] link in App Store engl/german

**Comment by JulianKahnert** [comment]
My Intention: it should be obvious where a user can find
* the FAQs > FAQ Wiki Page
* help, if needed > Slack Helpdesk Channel and via support@pdf-archiver.io
* submit feature requests > feature-request@pdf-archiver.io

**Comment by janwh** [comment]
Ah! 🤦‍♂️  I thought the FAQ should be on a subpage on the website. Thanks for clarifying!

**Comment by janwh** [comment]
Sure! I'll be swamped over the weekend, will get to it on Tuesday, if that's okay.
