### ISSUE TITLE
fix minor glitches

### ISSUE THREAD

**Issue by JulianKahnert** [PDF-Archiver/pdf-archiver.github.io#7]
* [x] Mac App Store Badge on en website
* [x] On german website: change Archivar to Archiver
* [ ] Maybe some Icon with the second color of the [Simple Theme](https://color.adobe.com/de/Simple-Theme-color-theme-10451401/)

**Comment by janwh** [comment]
I will pull out the third issue into a separate ticket, since I would like to better incorporate all theme colors into the template properly. That will take a little more time.
